### PR TITLE
0.17.1

### PR DESCRIPTION
**Pull request by adyach**
Non-json payloads on error responses are handled [#364](https://github.com/dehora/nakadi-java/pull/364)

### CODE REVIEW

**Comment by adyach** [comment]
@dehora releasing the fix, please, merge

**Comment by ePaul** [comment]
:+1:

**Comment by dehora** [comment]
@adyach can you move this to 0.18.0 please. This isn't a bug fix.

**Comment by adyach** [comment]
thanks @dehora  !

**Pull request closed without merging**
